config/routes.rb
Rails.application.routes.draw do

  root 'user#index', as: :users

  get 'show/:id' => 'user#show', as: :user

  post 'mailr/' => 'mailr#create', as: :new_mailr 

  patch 'show/:id' => 'mailr#update'

end

app/models/mailr.rb
class Mailr < ActiveRecord::Base
	belongs_to :user

	# The Magaic - Unveiled
	# def init
	# 	@user_id = integer
	# end

	# def user
	# 	User.find(@user_id)
	# end

	# so that Message.user => User

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :message

	#THE MAGIC REALIZED:
	# def initialize
	# 	@id = id
	# end

	# def messages
	# 	Message.where(user_id: @id)
	# end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mailr_controller.rb
class MailrController < ApplicationController

  def create
  	# user_1 = params[:mailr][:user1]
  	# raise user_1.inspect 
	@message = Mailr.new(mailr_params)
	if @message.save
	    redirect_to :back
  	end
  end

  def update
  	@message = Mailr.find(params[:id])
  	if @message.update_attributes(mailr_params)
  		redirect_to users_path(params[:id])
  	else
  		render :edit
  	end
  end

    private
	def mailr_params
		params.require(:mailr).permit(:message, :user1, :user2)
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  
  def index
    @current_user = User.first
  	@users = User.all[1..-1]
  end

  def show
  	@messages = Mailr.all
  	@current_user = User.find(params[:id])
  	@users = User.all
  	@message = Mailr.new
  end

  def new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/mailr_helper.rb
module MailrHelper
end

app/helpers/user_helper.rb
module UserHelper

  def ago_in_words(created_at)
    return 'a very very long time ago' if created_at.year < 1800
    secs = Time.now - created_at
    return 'just now' if secs > -1 && secs < 1
    return '' if secs <= -1
    pair = ago_in_words_pair(secs)
    ary = ago_in_words_singularize(pair)
    ary.size == 0 ? '' : ary.join(' and ') << ' ago'
  end

    private

  # @private
  def ago_in_words_pair(secs)
    [[60, :seconds], [60, :minutes], [24, :hours], [100_000, :days]].map{ |count, name|
      if secs > 0
        secs, n = secs.divmod(count)
        "#{n.to_i} #{name}"
      end
    }.compact.reverse[0..1]
  end

  # @private
  def ago_in_words_singularize(pair)
    if pair.size == 1
      pair.map! {|part| part[0, 2].to_i == 1 ? part.chomp('s') : part }
    else
      pair.map! {|part| part[0, 2].to_i == 1 ? part.chomp('s') : part[0, 2].to_i == 0 ? nil : part }
    end
    pair.compact
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mail Room</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="super-top-nav rl-padding">
		<a style="color: white" href="http://localhost:3000/"><span class='glyphicon glyphicon-home glyph-lg' style='float:left; padding-top: 10px; font-size: 2.2em;'></span></a>
		<span class="rl-padding" style="text-align: right"><b>Welcome, <%= User.find(1).name %>!</b></span>
		<button type='button' class='btn navbar-btn bg-gray'><%= link_to "Log Out", users_path %></button>
	</div>

	<div class="jumbotron rl-padding">
		<h1 style="color: #c41111">Mail Room</h1>
	</div>

	<div style="width: 80%" class="center-block">
		<%= yield %>
	</div>

<br><br>
<div class="verticaltext">
Designed using Bootstrap and Rails by Juli Emmel
</div>
</body>

</html>

app/views/user/index.html.erb
<div style="width: 90%">

<%= link_to ("<button type='button' class='btn btn-primary btn-lg btn-block'>Go to Your Mailbox</button>").html_safe, user_path(@current_user.id) %>

<br><br>

<h3>Other Mailboxes:</h3> 

	<% @users.each do |f| %>
	<button type="button" class="btn btn-primary btn-lg btn-block">
	<%= link_to f.name, user_path(f.id) %>	
	</button>
	<% end %>

</div>

app/views/user/show.html.erb
<h1><%= @current_user.name %>'s Messages</h1>
 
<p>Displaying all of <%= @current_user.name %>'s Messages:</p>

<div class="rounded">
<% @messages.where('user1=? OR user2=?', @current_user.id, @current_user.id).each do |f| %>
 <p><strong><%= f.message %></strong> <span style="float: right; padding-right: 125px;"><i>(sent <%= ago_in_words(f.created_at) %> to <%= @users.find(f.user2).name %> from <%= @users.find(f.user1).name %>)</i></span><hr><br><br> 
 <% end %>

</div> 

<div class="rounded" style="margin-top: 50px">
	<h3>Send Message to <%= @current_user.name %> </h3>
	<%= form_for Mailr.new, url: new_mailr_path do |f| %>
		<%= f.text_area :message, size: "80x15" %><br>
		<%= f.hidden_field :user1, :value => "1" %>
		<%= f.hidden_field :user2, :value => @current_user.id %> 
		<%= f.submit "Send Message" %>
		<% end %>
</div>